---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
tabs:
  - name: "Monitor" # tab 1
    direction: Horizontal
    focus: true
    parts:
      - direction: Horizontal
        borderless: false
        split_size:
          Fixed: 26
        run:
          command: {cmd: btop, args: ["-p","1"]}
      - direction: Vertical
        parts:
          - direction: Horizontal
            focus: true
          - direction: Horizontal
            split_size:
              Fixed: 70
            run:
              command: {cmd: btop, args: ["-p","2"]}
  - name: "Tab #2" # tab 2
    direction: Horizontal
