#!/usr/bin/env bash
#
# vim: ts=2 sw=2 et ff=unix ft=bash syntax=sh

function _nredf_zplug() {
  ZPLUG_HOME="${NREDF_RC_PATH}/zplug"
  ZPLUG_PLUGINS="${NREDF_RC_PATH}/plugins"
  if [[ -f "${NREDF_CONFIG}/shell/${NREDF_SHELL_NAME}/plugins" ]]; then
    ZPLUG_LOADFILE="${NREDF_CONFIG}/shell/${NREDF_SHELL_NAME}/plugins"
  else
    touch "${NREDF_CONFIG}/shell/${NREDF_SHELL_NAME}/plugins"
    ZPLUG_LOADFILE="${NREDF_CONFIG}/shell/${NREDF_SHELL_NAME}/plugins"
  fi

  if [[ -f "${ZPLUG_HOME}/init.zsh" ]]; then
    source "${ZPLUG_HOME}/init.zsh"
    source "${ZPLUG_PLUGINS}"
    source "${ZPLUG_LOADFILE}"

    if [[ -z ${SUDO_COMMAND} ]]; then
      if ! zplug check; then
        zplug install
      fi

      if ! _nredf_last_run; then
        zplug update
        _nredf_last_run "" "true"
      fi
    fi

    # source plugins and add commands to the PATH
    zplug load
  else
    echo -e '\033[1mSetup zplug\033[0m'
    [[ -d "${ZPLUG_HOME}" ]] && rm -rf "${ZPLUG_HOME}"
    git clone https://github.com/zplug/zplug "${ZPLUG_HOME}"
    source "${ZPLUG_HOME}/init.zsh"
    source "${ZPLUG_PLUGINS}"
    source "${ZPLUG_LOADFILE}"
    zplug install
    zplug load
    _nredf_last_run "" "true"
  fi
}
