#!/usr/bin/env zsh
#
# vim: ts=2 sw=2 et ff=unix ft=bash syntax=sh
# shellcheck disable=SC1071

[[ ! -d "${XDG_STATE_HOME}/zsh" ]] && mkdir -p "${XDG_STATE_HOME}/zsh"
[[ ! -d "${XDG_CACHE_HOME}/zsh" ]] && mkdir -p "${XDG_CACHE_HOME}/zsh"
fpath=("${HOME}/.config/completion/zsh" "${fpath[@]}")

source "${NREDF_RC_PATH}/bindings"

_nredf_zplug
source "${ZPLUG_PLUGINS}"
source "${ZPLUG_LOADFILE}"

export HISTFILE="${XDG_STATE_HOME}"/zsh/history
rm -f "${HOME}/.zcompdump"
compinit -u -d "${HOME}/.zcompdump"
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME}/zsh/zcompcache"
zstyle -e ':completion:*' special-dirs '[[ $PREFIX = (../)#(|.|..) ]] && reply=(..)'
zmodload zsh/mathfunc
