#!/usr/bin/env zsh
#
# vim: ts=2 sw=2 et ff=unix ft=bash syntax=sh
# shellcheck disable=SC1071

[[ ! -d "${XDG_STATE_HOME}/zsh" ]] && mkdir -p "${XDG_STATE_HOME}/zsh"
[[ ! -d "${XDG_CACHE_HOME}/zsh" ]] && mkdir -p "${XDG_CACHE_HOME}/zsh"
fpath=("${HOME}/.config/completion/zsh" "${fpath[@]}")

if (( ! ${+functions[_nredf_zplug]} )); then
	[[ -z "${NREDF_RC_PATH}" && -n "${NREDF_DOT_PATH}" && -n "${NREDF_SHELL_NAME}" ]] && export NREDF_RC_PATH="${NREDF_DOT_PATH}/shell/${NREDF_SHELL_NAME}"
	if (( ! ${+functions[_nredf_init_paths]} )) && [[ -n "${NREDF_DOT_PATH}" ]]; then
		source "${NREDF_DOT_PATH}/shell/common/functions/nredf_init_paths.bash"
	fi
	(( ${+functions[_nredf_init_paths]} )) && _nredf_init_paths
	[[ -n "${NREDF_RC_PATH}" && -f "${NREDF_RC_PATH}/functions" ]] && source "${NREDF_RC_PATH}/functions"
fi

_nredf_zplug

export HISTFILE="${XDG_STATE_HOME}"/zsh/history
rm -f "${HOME}/.zcompdump"
autoload -Uz compinit
compinit -u -d "${HOME}/.zcompdump"
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME}/zsh/zcompcache"
zstyle -e ':completion:*' special-dirs '[[ $PREFIX = (../)#(|.|..) ]] && reply=(..)'
zmodload zsh/mathfunc
