plugin:
  #get all resources in a namespace using the krew get-all plugin
  get-all:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - "kubectl get-all -n $NAMESPACE --context $CONTEXT | less"

  veleroBackupLogs:
    shortCut: l
    confirm: false
    description: Velero backup logs
    scopes:
    - backup
    - backups
    - velero.io/v1/backups
    command: sh
    background: false
    args:
    - -c
    - "velero backup logs $NAME --kubecontext $CONTEXT | less"

  veleroBackupDescribe:
    shortCut: Ctrl-L
    confirm: false
    description: Velero describe backup
    scopes:
    - backup
    - backups
    - velero.io/v1/backups
    command: sh
    background: false
    args:
    - -c
    - "velero backup describe $NAME --kubecontext $CONTEXT | less"

