#!/usr/bin/env bash

# Only proceed when running under WSL; otherwise, exit/return quietly
if [[ -z "${WSL_DISTRO_NAME:-}" ]] && ! grep -qiE "(microsoft|wsl)" /proc/sys/kernel/osrelease 2>/dev/null; then
  NREDF_DOT_PATH="${HOME}/.homesick/repos/dotfiles"
  NREDF_CONFIG="${HOME}/.config/nredf"
  if [[ -e "${NREDF_DOT_PATH}/shell/common/functions/nredf_set_ssh_agent.bash" ]]; then
    source "${NREDF_DOT_PATH}/shell/common/scripts/nredf_config.bash"
    if [[ -e "${NREDF_CONFIG}/config.bash" ]]; then
      unset NREDF_CONFIGS
      declare -A NREDF_CONFIGS
      source "${NREDF_CONFIG}/config.bash"
    fi
    source "${NREDF_DOT_PATH}/shell/common/functions/nredf_set_ssh_agent.bash"

    nredf_set_ssh_agent
  fi
fi
